#!/bin/bash

alias reload='. ~/.dotfiles/aliases'

source ~/.dotfiles/functions

alias ..='cd ..'
alias ...='cd ../..'
alias -- -='cd -'

alias ls='ls -F --color=auto'
alias l='ls -lAh'
alias la='ls -Al'

alias tree='tree -C'
alias trls='tree -C | less -R' # -C outputs colour, -R makes less understand color

# shortcuts
alias t='docker run --rm -ti -v /etc/localtime:/etc/localtime -v ~/.timetrap.db:/root/.timetrap.db walm/timetrap'
alias e='nvim'
alias h='history'
alias g='git'
alias d='docker'
alias dc-up='docker-compose up'
alias dc-run='docker-compose run'
alias week='date +%V'
alias sync-time='sudo ntpd -qg'
alias calw='gcalcli calw'
alias calm='gcalcli calm'
alias ping='ping -c 5' # ping 5 times ‘by default’
alias todos='ag "TODO:|FIXME:"'
alias mode='(set -o | grep emacs.*on >/dev/null 2>&1 && echo "emacs mode" || echo "vi mode")'
alias capture='maim -s -c 1,0,0,0.6 ~/Downloads/capture-$(date +%F-%T).png'

# ex. go test . | colorize
alias colorize="sed ''/PASS/s//$(printf \"\\033[32mPASS\\033[0m\")/'' | sed ''/FAIL/s//$(printf \"\\033[31mFAIL\\033[0m\")/'' | sed ''/SKIP/s//$(printf \"\\033[34mSKIP\\033[0m\")/''"

# stoptimer
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'
alias pubip='dig +short myip.opendns.com @resolver1.opendns.com'


if [[ "$OSTYPE" == "darwin"* ]]; then
  alias ql='qlmanage -p 2>/dev/null' # preview a file using QuickLook
else # assume linux

  ql() {
    if [[ "$1" == *".pdf" ]]; then
      zathura --mode=fullscreen "$@"
    else
      if command -v gpicview 2>/dev/null; then
        gpicview "$@"
      else
        feh "$@"
      fi
    fi
  }

fi

