#!/bin/bash

# completion (on linux it most likely will be loaded in /etc/bash.bashrc)
# but that's not the case for mac, so load it
if [[ -r /usr/local/etc/bash_completion ]]; then . /usr/local/etc/bash_completion; fi

# complete g as git
complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null

# complete d as docker
complete -o bashdefault -o default -o nospace -F _docker d 2>/dev/null
