#!/bin/bash

# color man
man() {
  # what can be set, use LESS_TERMCAP_DEBUG=1
  env LESS_TERMCAP_mb=$'\E[01;31m' \
  LESS_TERMCAP_md=$'\E[01;38;5;74m' \
  LESS_TERMCAP_me=$'\E[0m' \
  LESS_TERMCAP_so=$'\E[01;33m' \
  LESS_TERMCAP_se=$'\E[0m' \
  LESS_TERMCAP_ue=$'\E[0m' \
  LESS_TERMCAP_us=$'\E[04;38;5;146m' \
  man "$@"
}

# set environment for docker-machines and store it for next login
dm-env() {
  docker-machine env "$1" > ~/.docker-machine-env
  source ~/.docker-machine-env
}

# create a dir and cd it
take() {
  mkdir -p "$1"
  cd "$1" || exit
}

# start webserver in current dir
webserver() {
  local port="${1:-5000}"
  ruby -run -e httpd . -p${port}
}

# pretty json
pjson() {
  if [ -t 0 ]; then # argument
    python -mjson.tool <<< "$*" | pygmentize -l javascript
  else # pipe
    python -mjson.tool | pygmentize -l javascript
  fi
}

