#!/bin/bash

export GOROOT=/usr/lib/go
# mac brew
[[ -d /usr/local/opt/go/libexec ]] && export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/src/gocode

export PATH=$GOPATH/bin:$PATH
export PATH=$GOROOT/bin:$PATH
export PATH=~/.gem/ruby/2.4.0/bin:$PATH
export PATH=~/.rbenv/bin:$PATH
export PATH=~/.node_modules_global/bin:$PATH
export PATH=~/bin:~/.local/bin:$PATH
