# -- reload config with <C-a> R
# -- install and reload <C-a> I

# -- plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @resurrect-processes 'ssh autossh mosh-client'
set -g @plugin 'tmux-plugins/tmux-continuum' #automatically save sessions every 15mins
set -g @continuum-restore 'off'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

# -- image preview fix for yazi
# https://yazi-rs.github.io/docs/image-preview/#tmux
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# -- ctrl-a as prefix
unbind-key C-b
set -g prefix C-a

# -- base index to 1
setw -g base-index 1
setw -g pane-base-index 1

# -- resize to smallest active client
setw -g aggressive-resize on
setw -g window-size latest

# -- don't rename window names
setw -g automatic-rename off

# -- report multi mod keys
set -g extended-keys on
set -g extended-keys-format csi-u

# -- status bar
set -g status-position top
set -g status-bg '#212226'
set -g status-fg '#4C566A'
set -g status-left-length 20
set -g status-left '    #[fg=#81A1C1]#S  #[fg=#000000]╱'
# inactive windows
set-window-option -g window-status-format '   #I #W    #[fg=#000000]'
# current or active window
set-window-option -g window-status-current-format '   #I #[fg=#81A1C1]#W    #[fg=#000000]'
# alerted window in status bar
set-window-option -g window-status-bell-style fg=white,bg=white
set -g status-right '#[fg=#000000]#[fg=#4C566A]   %Y-%m-%d %H:%M    '
# pane border colors
# set-option -g pane-active-border-style fg=black
# set-option -g pane-border-style fg=brightblack


# -- vi mode
setw -g mode-keys vi
set-option -g status-keys vi
set-window-option -g mode-keys vi

# -- easy copy mode
bind-key u copy-mode
unbind-key [
bind-key p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'Escape' send -X cancel
bind-key -T copy-mode-vi 'y' send -X copy-selection
# bind-key y run "tmux save-buffer - | xclip -selection clipboard"

# windows / session picker
bind-key Space display-popup -E -w 80% 'tmux switch-client -t "$(tv tmux-windows)"'

# -- don't change circle layouts
# this is now set to windows / session picker
# unbind-key Space

# -- circle windows
unbind-key C-o
bind-key g rotate

# -- move to last window (faster then C-a a that tmux-sensible use)
unbind-key a
bind-key C-a last-window

# -- create window with name prompt
bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# -- create panes like vim window
bind-key s split-window
bind-key v split-window -h

# -- rebind choose-session as S
# bind-key S choose-session
bind-key S display-popup -E -w 60% 'tmux switch-client -t "$(tv tmux-sessions)"'

# -- toggle mouse off/on with M
set -g mouse off # default
bind-key M set -g mouse\; display-message "mouse is now #{?mouse,on,off}"

# undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
