#!/bin/zsh
set -e

# tag based on folder name
for f in `ls`; do
  f=$f:gs/\///
  /usr/local/bin/notmuch tag +$f folder:$f and not tag:$f
done

# fix special tags
/usr/local/bin/notmuch tag -starred tag:starred
/usr/local/bin/notmuch tag +★ folder:starred and not tag:★
/usr/local/bin/notmuch tag -INBOX tag:INBOX
/usr/local/bin/notmuch tag -important tag:important
/usr/local/bin/notmuch tag -inbox tag:inbox and not folder:INBOX

