#!/bin/zsh
set -e

# tag based on folder name
for f in `ls`; do
  f=$f:gs/\///
  if [ $f != 'all_mail' ]; then
    echo $f
    /usr/local/bin/notmuch tag +$f folder:$f and not tag:$f
  fi
done

# remove some tags
/usr/local/bin/notmuch tag -INBOX tag:INBOX
/usr/local/bin/notmuch tag -important tag:important
/usr/local/bin/notmuch tag -all_mail tag:all_mail
/usr/local/bin/notmuch tag -inbox not folder:INBOX
/usr/local/bin/notmuch tag +inbox folder:INBOX


